const bcrypt = require("bcrypt");

module.exports.predefinedRoles = [
  { id: 1, role: "Site super admin" },
  { id: 2, role: "Super admin" },
  { id: 3, role: "Manager" },
  { id: 4, role: "Content contributor" },
  { id: 5, role: "Member" },
];
module.exports.preDefinedDocumentLevel = [
  { id: 1, level: 1 },
  { id: 2, level: 2 },
];
module.exports.perMissions = [
  {
    id: "1",
    PermissionName: "All Resources ",
  },
  {
    id: "2",
    PermissionName: "Restricted resources",
  },
];

const salt = bcrypt.genSaltSync(10, "a");
module.exports.users = [
  {
    id: 1,
    firstName: "Super Admin",
    lastName: "1",
    username: "Super Admin",
    email: "superadmin@yopmail.com",
    company: "abc",
    address: "#abc location,xyz",
    country: "america",
    state: "verginia",
    city: "verginia",
    zipcode: 16010,
    phone: 9845781523,
    password: bcrypt.hashSync("password", salt),
    status: 1,
    verificationToken: true,
    isVerified: true,
  },
  {
    id: 2,
    firstName: "Manager",
    lastName: "1",
    username: "Manager 1",
    email: "manager@yopmail.com",
    company: "abc",
    address: "#abc location,xyz",
    country: "america",
    state: "verginia",
    city: "verginia",
    zipcode: 16010,
    phone: 1234567891,
    password: bcrypt.hashSync("password", salt),
    status: 1,
    verificationToken: true,
    isVerified: true,
  },
  {
    id: 3,
    firstName: "Site Super Admin",
    lastName: "1",
    username: "Site Super Admin 1",
    email: "sitesuperadmin@yopmail.com",
    company: "abc",
    address: "#abc location,xyz",
    country: "america",
    state: "verginia",
    city: "verginia",
    zipcode: 16010,
    phone: 1234567891,
    password: bcrypt.hashSync("password", salt),
    status: 1,
    verificationToken: true,
    isVerified: true,
  },
  {
    id: 4,
    firstName: "Member",
    lastName: "1",
    username: "Member 1",
    email: "member@yopmail.com",
    company: "abc",
    address: "#abc location,xyz",
    country: "america",
    state: "verginia",
    city: "verginia",
    zipcode: 160104,
    phone: 1234567891,
    password: bcrypt.hashSync("password", salt),
    status: 1,
    verificationToken: true,
    isVerified: true,
  },
  {
    id: 5,
    firstName: "Content Contributor",
    lastName: "1",
    username: "Content 1",
    email: "contentcontributor@yopmail.com",
    company: "abc",
    address: "#abc location,xyz",
    country: "america",
    state: "verginia",
    city: "verginia",
    zipcode: 160104,
    phone: 1234567891,
    password: bcrypt.hashSync("password", salt),
    status: 1,
    verificationToken: true,
    isVerified: true,
  },
];

module.exports.assignRole = [
  { id: 1, userId: 1, roleId: 2 },
  { id: 2, userId: 2, roleId: 3 },
  { id: 3, userId: 3, roleId: 1 },
  { id: 4, userId: 4, roleId: 5 },
  { id: 5, userId: 5, roleId: 4 },
];
